import { useState } from 'react'
import { Button, EmptyState, Field, Icon, Modal, ModalActions, PageHeading, StatusChip } from '../components/ui/index.jsx'

export default function ServicesPage({ doctors, services, offerings, busy, onCreateService, onCreateOffering, onToggleService, onToggleOffering, onError }) {
  const [dialog, setDialog] = useState('')
  const [serviceForm, setServiceForm] = useState({ name: '', description: '' })
  const [offeringForm, setOfferingForm] = useState({ doctorId: '', serviceId: '', fee: '', durationMinutes: '30' })
  const updateService = (key) => (event) => setServiceForm((current) => ({ ...current, [key]: event.target.value }))
  const updateOffering = (key) => (event) => setOfferingForm((current) => ({ ...current, [key]: event.target.value }))
  async function submitService(event) {
    event.preventDefault()
    try { await onCreateService(serviceForm); setDialog(''); setServiceForm({ name: '', description: '' }) } catch (error) { onError(error.message) }
  }
  async function submitOffering(event) {
    event.preventDefault()
    try { await onCreateOffering({ ...offeringForm, fee: Number(offeringForm.fee), durationMinutes: Number(offeringForm.durationMinutes) }); setDialog('') } catch (error) { onError(error.message) }
  }
  const activeOfferings = offerings.filter((item) => item.isActive)
  return <><PageHeading title="Services & fees" description="Create clinic services, then set a provider, fee, and appointment length." action={<div className="toolbar-actions"><Button variant="outline" onClick={() => setDialog('offering')}><Icon name="plus" size={15}/>Add offering</Button><Button onClick={() => setDialog('service')}><Icon name="plus" size={15}/>Add service</Button></div>}/>
    <section className="panel table-panel"><div className="table-heading"><div><h2>Appointment offerings</h2><p>Provider-specific fees and visit lengths.</p></div><span className="table-count">{activeOfferings.length}</span></div>{activeOfferings.length ? <div className="offering-list">{activeOfferings.map((item) => <div className="offering-item" key={item._id}><div className="offering-label"><strong>{item.serviceId?.name || 'Service'}</strong><small>{item.doctorId?.name || 'Professional'}</small></div><span>{item.durationMinutes} min</span><strong>₹{Number(item.fee).toLocaleString('en-IN')}</strong><button className="plain-link" onClick={() => onToggleOffering(item, false)}>Deactivate</button></div>)}</div> : <EmptyState title="No offerings yet" body="Add a service and pair it with a care professional to set fees and duration." action={services.length ? 'Add offering' : 'Add a service'} onAction={() => setDialog(services.length ? 'offering' : 'service')}/>}</section>
    <section className="panel table-panel catalogue-panel"><div className="table-heading"><div><h2>Service catalogue</h2><p>Services available at your clinic.</p></div><Button variant="quiet" onClick={() => setDialog('service')}><Icon name="plus" size={15}/>Add service</Button></div>{services.map((service) => <div className="catalogue-item" key={service._id}><div><strong>{service.name}</strong><small>{service.description || 'No description'}</small></div><StatusChip tone={service.isActive ? 'black' : 'neutral'}>{service.isActive ? 'Active' : 'Inactive'}</StatusChip><button className="plain-link" onClick={() => onToggleService(service, !service.isActive)}>{service.isActive ? 'Deactivate' : 'Activate'}</button></div>)}{!services.length && <p className="empty-inline">No services in the catalogue yet.</p>}</section>
    {dialog === 'service' && <Modal eyebrow="SERVICE CATALOGUE" title="Add service" onClose={() => setDialog('')}><form className="stack-form" onSubmit={submitService}><Field label="Service name" value={serviceForm.name} onChange={updateService('name')} required minLength={2}/><label className="field"><span>Description</span><textarea rows="3" value={serviceForm.description} onChange={updateService('description')} placeholder="A short service description"/></label><ModalActions busy={busy} onCancel={() => setDialog('')} submit="Add service"/></form></Modal>}
    {dialog === 'offering' && <Modal eyebrow="PROVIDER PRICING" title="Add appointment offering" onClose={() => setDialog('')}><form className="stack-form" onSubmit={submitOffering}><label className="field"><span>Professional</span><select value={offeringForm.doctorId} onChange={updateOffering('doctorId')} required><option value="">Choose professional</option>{doctors.filter((item) => item.isActive).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="field"><span>Service</span><select value={offeringForm.serviceId} onChange={updateOffering('serviceId')} required><option value="">Choose service</option>{services.filter((item) => item.isActive).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><div className="form-grid"><Field label="Fee (INR)" type="number" min="0" value={offeringForm.fee} onChange={updateOffering('fee')} required/><Field label="Duration (minutes)" type="number" min="5" max="480" value={offeringForm.durationMinutes} onChange={updateOffering('durationMinutes')} required/></div><ModalActions busy={busy} onCancel={() => setDialog('')} submit="Save offering"/></form></Modal>}
  </>
}
